global:
  scrape_interval: 15s # Coleta dados a cada 5 segundos

scrape_configs:
  - job_name: 'nestjs-api'
    static_configs:
      # IMPORTANTE: 'api' deve ser o nome do serviço da sua aplicação no docker-compose
      # Se sua api roda local fora do docker, use 'host.docker.internal:3000'
      - targets: ['api:3000'] 
    metrics_path: '/metrics'